### ISSUE TITLE
Implement GameObject Class

### ISSUE THREAD

**Issue by MandipSan** [MandipSan/00Driver#2]

**Comment by MandipSan** [comment]
I changed the gameobject class x, y, width, height to now be a rect box where the left, top, right, bottom are used instead to make it easier to animate. The image for the objects are now going to be one large sheet with all the images for one object on it so that each object has one sheet per object. The exact details of how the sheet is going to be draw is will be layout in out in it design document that I will create. The class also now has animation state to help with pulling the out the right frame for the right situation. The class still need to be test which I will in a bit. The changes shouldn't have to much of an effect on the other class that inherit from it.

**Comment by MandipSan** [comment]
All the implementation for this class and test is done. Just need look over to check to make sure nothing was missed from the MIS. Then ready to merge into master.

**Comment by mjreffel** [comment]
Modified GameObject class to overload the constructor so that the game object can take as input an image reference, as well as that images width and height to reduce repeated code across the platform as every object would need an image and the width and height are required for the animation class. Also reopening for now as more might need to be added as we progress forward.

**Comment by MandipSan** [comment]
Complete and integrated into master branch
